#!/bin/bash
#SBATCH -J hdf5test # job name
#SBATCH -o /bsuhome/zacharykeskinen/uavsar/logs/log.%x.o%j # output and error file name (%j expands to jobID)
#SBATCH -n 4 # total number of tasks requested
#SBATCH -N 4 # number of nodes you want to run on
#SBATCH -p bsudfq # queue (partition)
#SBATCH -t 3:00:00 # run time (hh:mm:ss) - 1 minute in this example.

eval "$(conda shell.bash hook)"
conda activate proj

python ~/uavsar/src/play/hdf5.py