#!/bin/bash
#SBATCH -J updated_metloom # job name
#SBATCH -o /bsuhome/zacharykeskinen/uavsar/logs/log.%x.o%j # output and error file name (%j expands to jobID)
#SBATCH -n 48 # total number of tasks requested
#SBATCH -N 1 # number of nodes you want to run on
#SBATCH -p bsudfq # queue (partition)
#SBATCH -t 00:30:00 # run time (hh:mm:ss) - 1 hour in this example.

eval "$(conda shell.bash hook)"
conda activate proj

python ~/uavsar/src/uavsar_snotel_sd/riox_snotel_coh.py